name: Start release
on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Branch name, tag name or commit SHA to release'
        required: true
        default: 'main'
        type: string
      release_version:
        description: 'Release version in the format YYYY-MM-DD.N'
        required: true
        default: 'YYYY-MM-DD.1'
        type: string

jobs:
  prepare-release-pr:
    runs-on: ubuntu-latest
    name: Prepare release PR
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Create Release Candidate branch
      uses: peterjgrainger/action-create-branch@v2.3.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        branch: 'rc-${{ inputs.release_version }}'
        sha: '${{ inputs.commit }}'

    - name: Open a pull request
      id: pull
      uses: tretuna/sync-branches@1.4.0
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        FROM_BRANCH: 'rc-${{ inputs.release_version }}'
        TO_BRANCH: "stage"
